//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.19 at 11:10:14 AM CST 
//


package au.org.ecoinformatics.eml.jaxb.sysmeta;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Represents a list of :term:`checksum`
 *       algorithms.
 * 
 * <p>Java class for ChecksumAlgorithmList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ChecksumAlgorithmList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="algorithm" type="{http://ns.dataone.org/service/types/v1}ChecksumAlgorithm" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChecksumAlgorithmList", propOrder = {
    "algorithms"
})
@XmlRootElement(name = "checksumAlgorithmList")
public class ChecksumAlgorithmList {

    @XmlElement(name = "algorithm", required = true)
    protected List<String> algorithms;

    /**
     * Gets the value of the algorithms property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the algorithms property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAlgorithms().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getAlgorithms() {
        if (algorithms == null) {
            algorithms = new ArrayList<String>();
        }
        return this.algorithms;
    }

    public ChecksumAlgorithmList withAlgorithms(String... values) {
        if (values!= null) {
            for (String value: values) {
                getAlgorithms().add(value);
            }
        }
        return this;
    }

    public ChecksumAlgorithmList withAlgorithms(Collection<String> values) {
        if (values!= null) {
            getAlgorithms().addAll(values);
        }
        return this;
    }

}
