//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.19 at 11:10:14 AM CST 
//


package au.org.ecoinformatics.eml.jaxb.sysmeta;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The available Dataone Service APIs that are exposed on
 *       a Node. Without a restriction, all service methods are available to all
 *       callers. Restrictions may be placed on individual methods of the service
 *       to limit the service to a certain set of :term:`Subjects`. Enforcement
 *       of these service restrictions is incumbent on the Node service
 *       implementation.
 * 
 * <p>Java class for Service complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Service">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="restriction" type="{http://ns.dataone.org/service/types/v1}ServiceMethodRestriction" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://ns.dataone.org/service/types/v1}ServiceName" />
 *       &lt;attribute name="version" use="required" type="{http://ns.dataone.org/service/types/v1}ServiceVersion" />
 *       &lt;attribute name="available" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Service", propOrder = {
    "restrictions"
})
@XmlRootElement(name = "service")
public class Service {

    @XmlElement(name = "restriction")
    protected List<ServiceMethodRestriction> restrictions;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "version", required = true)
    protected String version;
    @XmlAttribute(name = "available")
    protected Boolean available;

    /**
     * Gets the value of the restrictions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the restrictions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRestrictions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ServiceMethodRestriction }
     * 
     * 
     */
    public List<ServiceMethodRestriction> getRestrictions() {
        if (restrictions == null) {
            restrictions = new ArrayList<ServiceMethodRestriction>();
        }
        return this.restrictions;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the available property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAvailable() {
        return available;
    }

    /**
     * Sets the value of the available property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAvailable(Boolean value) {
        this.available = value;
    }

    public Service withRestrictions(ServiceMethodRestriction... values) {
        if (values!= null) {
            for (ServiceMethodRestriction value: values) {
                getRestrictions().add(value);
            }
        }
        return this;
    }

    public Service withRestrictions(Collection<ServiceMethodRestriction> values) {
        if (values!= null) {
            getRestrictions().addAll(values);
        }
        return this;
    }

    public Service withName(String value) {
        setName(value);
        return this;
    }

    public Service withVersion(String value) {
        setVersion(value);
        return this;
    }

    public Service withAvailable(Boolean value) {
        setAvailable(value);
        return this;
    }

}
