//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.19 at 11:10:14 AM CST 
//


package au.org.ecoinformatics.eml.jaxb.sysmeta;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Access control rules are specified by the
 *       :term:`Origin Member Node` when the object is first registered in
 *       DataONE. If no rules are specified at that time, then the object is
 *       deemed to be private and the only user with access to the object (read,
 *       write, or otherwise) is the :term:`Rights Holder`.
 * 
 * <p>Java class for AccessRule complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AccessRule">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="subject" type="{http://ns.dataone.org/service/types/v1}Subject" maxOccurs="unbounded"/>
 *         &lt;element name="permission" type="{http://ns.dataone.org/service/types/v1}Permission" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AccessRule", propOrder = {
    "subjects",
    "permissions"
})
@XmlRootElement(name = "accessRule")
public class AccessRule {

    @XmlElement(name = "subject", required = true)
    protected List<Subject> subjects;
    @XmlElement(name = "permission", required = true)
    protected List<Permission> permissions;

    /**
     * Gets the value of the subjects property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subjects property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubjects().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Subject }
     * 
     * 
     */
    public List<Subject> getSubjects() {
        if (subjects == null) {
            subjects = new ArrayList<Subject>();
        }
        return this.subjects;
    }

    /**
     * Gets the value of the permissions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the permissions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPermissions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Permission }
     * 
     * 
     */
    public List<Permission> getPermissions() {
        if (permissions == null) {
            permissions = new ArrayList<Permission>();
        }
        return this.permissions;
    }

    public AccessRule withSubjects(Subject... values) {
        if (values!= null) {
            for (Subject value: values) {
                getSubjects().add(value);
            }
        }
        return this;
    }

    public AccessRule withSubjects(Collection<Subject> values) {
        if (values!= null) {
            getSubjects().addAll(values);
        }
        return this;
    }

    public AccessRule withPermissions(Permission... values) {
        if (values!= null) {
            for (Permission value: values) {
                getPermissions().add(value);
            }
        }
        return this;
    }

    public AccessRule withPermissions(Collection<Permission> values) {
        if (values!= null) {
            getPermissions().addAll(values);
        }
        return this;
    }

}
