//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.19 at 11:10:18 AM CST 
//


package au.org.ecoinformatics.eml.jaxb.eml;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AudioVisual complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AudioVisual">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="publisher" type="{eml://ecoinformatics.org/party-2.1.1}ResponsibleParty"/>
 *         &lt;element name="publicationPlace" type="{eml://ecoinformatics.org/resource-2.1.1}NonEmptyStringType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="performer" type="{eml://ecoinformatics.org/party-2.1.1}ResponsibleParty" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ISBN" type="{eml://ecoinformatics.org/resource-2.1.1}NonEmptyStringType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AudioVisual", propOrder = {
    "publisher",
    "publicationPlace",
    "performer",
    "isbn"
})
public class AudioVisual {

    @XmlElement(required = true)
    protected ResponsibleParty publisher;
    protected List<String> publicationPlace;
    protected List<ResponsibleParty> performer;
    @XmlElement(name = "ISBN")
    protected String isbn;

    /**
     * Gets the value of the publisher property.
     * 
     * @return
     *     possible object is
     *     {@link ResponsibleParty }
     *     
     */
    public ResponsibleParty getPublisher() {
        return publisher;
    }

    /**
     * Sets the value of the publisher property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponsibleParty }
     *     
     */
    public void setPublisher(ResponsibleParty value) {
        this.publisher = value;
    }

    /**
     * Gets the value of the publicationPlace property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the publicationPlace property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPublicationPlace().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPublicationPlace() {
        if (publicationPlace == null) {
            publicationPlace = new ArrayList<String>();
        }
        return this.publicationPlace;
    }

    /**
     * Gets the value of the performer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the performer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPerformer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ResponsibleParty }
     * 
     * 
     */
    public List<ResponsibleParty> getPerformer() {
        if (performer == null) {
            performer = new ArrayList<ResponsibleParty>();
        }
        return this.performer;
    }

    /**
     * Gets the value of the isbn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISBN() {
        return isbn;
    }

    /**
     * Sets the value of the isbn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISBN(String value) {
        this.isbn = value;
    }

    public AudioVisual withPublisher(ResponsibleParty value) {
        setPublisher(value);
        return this;
    }

    public AudioVisual withPublicationPlace(String... values) {
        if (values!= null) {
            for (String value: values) {
                getPublicationPlace().add(value);
            }
        }
        return this;
    }

    public AudioVisual withPublicationPlace(Collection<String> values) {
        if (values!= null) {
            getPublicationPlace().addAll(values);
        }
        return this;
    }

    public AudioVisual withPerformer(ResponsibleParty... values) {
        if (values!= null) {
            for (ResponsibleParty value: values) {
                getPerformer().add(value);
            }
        }
        return this;
    }

    public AudioVisual withPerformer(Collection<ResponsibleParty> values) {
        if (values!= null) {
            getPerformer().addAll(values);
        }
        return this;
    }

    public AudioVisual withISBN(String value) {
        setISBN(value);
        return this;
    }

}
