//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.19 at 11:10:18 AM CST 
//


package au.org.ecoinformatics.eml.jaxb.eml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the au.org.ecoinformatics.eml.jaxb.eml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Tooltip_QNAME = new QName("eml://ecoinformatics.org/documentation-2.1.1", "tooltip");
    private final static QName _DataTable_QNAME = new QName("eml://ecoinformatics.org/dataTable-2.1.1", "dataTable");
    private final static QName _OtherEntity_QNAME = new QName("eml://ecoinformatics.org/entity-2.1.1", "otherEntity");
    private final static QName _SpatialVector_QNAME = new QName("eml://ecoinformatics.org/spatialVector-2.1.1", "spatialVector");
    private final static QName _Example_QNAME = new QName("eml://ecoinformatics.org/documentation-2.1.1", "example");
    private final static QName _SpatialRaster_QNAME = new QName("eml://ecoinformatics.org/spatialRaster-2.1.1", "spatialRaster");
    private final static QName _Text_QNAME = new QName("eml://ecoinformatics.org/text-2.1.1", "text");
    private final static QName _Description_QNAME = new QName("eml://ecoinformatics.org/documentation-2.1.1", "description");
    private final static QName _Methods_QNAME = new QName("eml://ecoinformatics.org/methods-2.1.1", "methods");
    private final static QName _Party_QNAME = new QName("eml://ecoinformatics.org/party-2.1.1", "party");
    private final static QName _Attribute_QNAME = new QName("eml://ecoinformatics.org/attribute-2.1.1", "attribute");
    private final static QName _Protocol_QNAME = new QName("eml://ecoinformatics.org/protocol-2.1.1", "protocol");
    private final static QName _Citation_QNAME = new QName("eml://ecoinformatics.org/literature-2.1.1", "citation");
    private final static QName _Access_QNAME = new QName("eml://ecoinformatics.org/access-2.1.1", "access");
    private final static QName _AttributeList_QNAME = new QName("eml://ecoinformatics.org/attribute-2.1.1", "attributeList");
    private final static QName _SpatialReference_QNAME = new QName("eml://ecoinformatics.org/spatialReference-2.1.1", "spatialReference");
    private final static QName _View_QNAME = new QName("eml://ecoinformatics.org/view-2.1.1", "view");
    private final static QName _Dataset_QNAME = new QName("eml://ecoinformatics.org/dataset-2.1.1", "dataset");
    private final static QName _ResearchProject_QNAME = new QName("eml://ecoinformatics.org/project-2.1.1", "researchProject");
    private final static QName _StoredProcedure_QNAME = new QName("eml://ecoinformatics.org/storedProcedure-2.1.1", "storedProcedure");
    private final static QName _Lineage_QNAME = new QName("eml://ecoinformatics.org/documentation-2.1.1", "lineage");
    private final static QName _Software_QNAME = new QName("eml://ecoinformatics.org/software-2.1.1", "software");
    private final static QName _Module_QNAME = new QName("eml://ecoinformatics.org/documentation-2.1.1", "module");
    private final static QName _Physical_QNAME = new QName("eml://ecoinformatics.org/physical-2.1.1", "physical");
    private final static QName _Summary_QNAME = new QName("eml://ecoinformatics.org/documentation-2.1.1", "summary");
    private final static QName _SoftwareTypeLicenseURL_QNAME = new QName("", "licenseURL");
    private final static QName _SoftwareTypeLicense_QNAME = new QName("", "license");
    private final static QName _ResponsiblePartyOrganizationName_QNAME = new QName("", "organizationName");
    private final static QName _ResponsiblePartyIndividualName_QNAME = new QName("", "individualName");
    private final static QName _ResponsiblePartyPositionName_QNAME = new QName("", "positionName");
    private final static QName _AccessTypeAllow_QNAME = new QName("", "allow");
    private final static QName _AccessTypeDeny_QNAME = new QName("", "deny");
    private final static QName _ParagraphTypeUlinkCitetitle_QNAME = new QName("", "citetitle");
    private final static QName _ParagraphTypeLiteralLayoutValue_QNAME = new QName("", "value");
    private final static QName _TextTypePara_QNAME = new QName("", "para");
    private final static QName _TextTypeSection_QNAME = new QName("", "section");
    private final static QName _ParagraphTypeLiteralLayout_QNAME = new QName("", "literalLayout");
    private final static QName _ParagraphTypeSuperscript_QNAME = new QName("", "superscript");
    private final static QName _ParagraphTypeSubscript_QNAME = new QName("", "subscript");
    private final static QName _ParagraphTypeUlink_QNAME = new QName("", "ulink");
    private final static QName _ParagraphTypeEmphasis_QNAME = new QName("", "emphasis");
    private final static QName _ParagraphTypeItemizedlist_QNAME = new QName("", "itemizedlist");
    private final static QName _ParagraphTypeOrderedlist_QNAME = new QName("", "orderedlist");
    private final static QName _PhysicalTypeCompressionMethod_QNAME = new QName("", "compressionMethod");
    private final static QName _PhysicalTypeEncodingMethod_QNAME = new QName("", "encodingMethod");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: au.org.ecoinformatics.eml.jaxb.eml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Eml }
     * 
     */
    public Eml createEml() {
        return new Eml();
    }

    /**
     * Create an instance of {@link ViewType }
     * 
     */
    public ViewType createViewType() {
        return new ViewType();
    }

    /**
     * Create an instance of {@link VectorDataQuality }
     * 
     */
    public VectorDataQuality createVectorDataQuality() {
        return new VectorDataQuality();
    }

    /**
     * Create an instance of {@link GeogCoordSysType }
     * 
     */
    public GeogCoordSysType createGeogCoordSysType() {
        return new GeogCoordSysType();
    }

    /**
     * Create an instance of {@link SpatialReferenceType }
     * 
     */
    public SpatialReferenceType createSpatialReferenceType() {
        return new SpatialReferenceType();
    }

    /**
     * Create an instance of {@link SpatialReferenceType.VertCoordSys }
     * 
     */
    public SpatialReferenceType.VertCoordSys createSpatialReferenceTypeVertCoordSys() {
        return new SpatialReferenceType.VertCoordSys();
    }

    /**
     * Create an instance of {@link HorizCoordSysType }
     * 
     */
    public HorizCoordSysType createHorizCoordSysType() {
        return new HorizCoordSysType();
    }

    /**
     * Create an instance of {@link HorizCoordSysType.ProjCoordSys }
     * 
     */
    public HorizCoordSysType.ProjCoordSys createHorizCoordSysTypeProjCoordSys() {
        return new HorizCoordSysType.ProjCoordSys();
    }

    /**
     * Create an instance of {@link HorizCoordSysType.ProjCoordSys.Projection }
     * 
     */
    public HorizCoordSysType.ProjCoordSys.Projection createHorizCoordSysTypeProjCoordSysProjection() {
        return new HorizCoordSysType.ProjCoordSys.Projection();
    }

    /**
     * Create an instance of {@link RasterDataQuality }
     * 
     */
    public RasterDataQuality createRasterDataQuality() {
        return new RasterDataQuality();
    }

    /**
     * Create an instance of {@link SpatialRasterType }
     * 
     */
    public SpatialRasterType createSpatialRasterType() {
        return new SpatialRasterType();
    }

    /**
     * Create an instance of {@link SpatialRasterType.GeoreferenceInfo }
     * 
     */
    public SpatialRasterType.GeoreferenceInfo createSpatialRasterTypeGeoreferenceInfo() {
        return new SpatialRasterType.GeoreferenceInfo();
    }

    /**
     * Create an instance of {@link ConstraintType }
     * 
     */
    public ConstraintType createConstraintType() {
        return new ConstraintType();
    }

    /**
     * Create an instance of {@link ConstraintType.NotNullConstraint }
     * 
     */
    public ConstraintType.NotNullConstraint createConstraintTypeNotNullConstraint() {
        return new ConstraintType.NotNullConstraint();
    }

    /**
     * Create an instance of {@link ConstraintType.JoinCondition }
     * 
     */
    public ConstraintType.JoinCondition createConstraintTypeJoinCondition() {
        return new ConstraintType.JoinCondition();
    }

    /**
     * Create an instance of {@link ConstraintType.UniqueKey }
     * 
     */
    public ConstraintType.UniqueKey createConstraintTypeUniqueKey() {
        return new ConstraintType.UniqueKey();
    }

    /**
     * Create an instance of {@link ConstraintType.PrimaryKey }
     * 
     */
    public ConstraintType.PrimaryKey createConstraintTypePrimaryKey() {
        return new ConstraintType.PrimaryKey();
    }

    /**
     * Create an instance of {@link NumericDomainType }
     * 
     */
    public NumericDomainType createNumericDomainType() {
        return new NumericDomainType();
    }

    /**
     * Create an instance of {@link NumericDomainType.Bounds }
     * 
     */
    public NumericDomainType.Bounds createNumericDomainTypeBounds() {
        return new NumericDomainType.Bounds();
    }

    /**
     * Create an instance of {@link DateTimeDomainType }
     * 
     */
    public DateTimeDomainType createDateTimeDomainType() {
        return new DateTimeDomainType();
    }

    /**
     * Create an instance of {@link DateTimeDomainType.Bounds }
     * 
     */
    public DateTimeDomainType.Bounds createDateTimeDomainTypeBounds() {
        return new DateTimeDomainType.Bounds();
    }

    /**
     * Create an instance of {@link Accuracy }
     * 
     */
    public Accuracy createAccuracy() {
        return new Accuracy();
    }

    /**
     * Create an instance of {@link NonNumericDomainType }
     * 
     */
    public NonNumericDomainType createNonNumericDomainType() {
        return new NonNumericDomainType();
    }

    /**
     * Create an instance of {@link NonNumericDomainType.EnumeratedDomain }
     * 
     */
    public NonNumericDomainType.EnumeratedDomain createNonNumericDomainTypeEnumeratedDomain() {
        return new NonNumericDomainType.EnumeratedDomain();
    }

    /**
     * Create an instance of {@link AttributeType }
     * 
     */
    public AttributeType createAttributeType() {
        return new AttributeType();
    }

    /**
     * Create an instance of {@link AttributeType.MeasurementScale }
     * 
     */
    public AttributeType.MeasurementScale createAttributeTypeMeasurementScale() {
        return new AttributeType.MeasurementScale();
    }

    /**
     * Create an instance of {@link MethodsType }
     * 
     */
    public MethodsType createMethodsType() {
        return new MethodsType();
    }

    /**
     * Create an instance of {@link MethodsType.Sampling }
     * 
     */
    public MethodsType.Sampling createMethodsTypeSampling() {
        return new MethodsType.Sampling();
    }

    /**
     * Create an instance of {@link PhysicalType }
     * 
     */
    public PhysicalType createPhysicalType() {
        return new PhysicalType();
    }

    /**
     * Create an instance of {@link PhysicalType.DataFormat }
     * 
     */
    public PhysicalType.DataFormat createPhysicalTypeDataFormat() {
        return new PhysicalType.DataFormat();
    }

    /**
     * Create an instance of {@link PhysicalType.DataFormat.BinaryRasterFormat }
     * 
     */
    public PhysicalType.DataFormat.BinaryRasterFormat createPhysicalTypeDataFormatBinaryRasterFormat() {
        return new PhysicalType.DataFormat.BinaryRasterFormat();
    }

    /**
     * Create an instance of {@link PhysicalType.DataFormat.TextFormat }
     * 
     */
    public PhysicalType.DataFormat.TextFormat createPhysicalTypeDataFormatTextFormat() {
        return new PhysicalType.DataFormat.TextFormat();
    }

    /**
     * Create an instance of {@link PhysicalType.DataFormat.TextFormat.Complex }
     * 
     */
    public PhysicalType.DataFormat.TextFormat.Complex createPhysicalTypeDataFormatTextFormatComplex() {
        return new PhysicalType.DataFormat.TextFormat.Complex();
    }

    /**
     * Create an instance of {@link ResearchProjectType }
     * 
     */
    public ResearchProjectType createResearchProjectType() {
        return new ResearchProjectType();
    }

    /**
     * Create an instance of {@link ResearchProjectType.StudyAreaDescription }
     * 
     */
    public ResearchProjectType.StudyAreaDescription createResearchProjectTypeStudyAreaDescription() {
        return new ResearchProjectType.StudyAreaDescription();
    }

    /**
     * Create an instance of {@link ResearchProjectType.StudyAreaDescription.Descriptor }
     * 
     */
    public ResearchProjectType.StudyAreaDescription.Descriptor createResearchProjectTypeStudyAreaDescriptionDescriptor() {
        return new ResearchProjectType.StudyAreaDescription.Descriptor();
    }

    /**
     * Create an instance of {@link ResponsibleParty }
     * 
     */
    public ResponsibleParty createResponsibleParty() {
        return new ResponsibleParty();
    }

    /**
     * Create an instance of {@link au.org.ecoinformatics.eml.jaxb.eml.TemporalCoverage }
     * 
     */
    public au.org.ecoinformatics.eml.jaxb.eml.TemporalCoverage createTemporalCoverage() {
        return new au.org.ecoinformatics.eml.jaxb.eml.TemporalCoverage();
    }

    /**
     * Create an instance of {@link SingleDateTimeType }
     * 
     */
    public SingleDateTimeType createSingleDateTimeType() {
        return new SingleDateTimeType();
    }

    /**
     * Create an instance of {@link GeographicCoverage }
     * 
     */
    public GeographicCoverage createGeographicCoverage() {
        return new GeographicCoverage();
    }

    /**
     * Create an instance of {@link GeographicCoverage.DatasetGPolygon }
     * 
     */
    public GeographicCoverage.DatasetGPolygon createGeographicCoverageDatasetGPolygon() {
        return new GeographicCoverage.DatasetGPolygon();
    }

    /**
     * Create an instance of {@link GeographicCoverage.BoundingCoordinates }
     * 
     */
    public GeographicCoverage.BoundingCoordinates createGeographicCoverageBoundingCoordinates() {
        return new GeographicCoverage.BoundingCoordinates();
    }

    /**
     * Create an instance of {@link au.org.ecoinformatics.eml.jaxb.eml.TaxonomicCoverage }
     * 
     */
    public au.org.ecoinformatics.eml.jaxb.eml.TaxonomicCoverage createTaxonomicCoverage() {
        return new au.org.ecoinformatics.eml.jaxb.eml.TaxonomicCoverage();
    }

    /**
     * Create an instance of {@link au.org.ecoinformatics.eml.jaxb.eml.TaxonomicCoverage.TaxonomicSystem }
     * 
     */
    public au.org.ecoinformatics.eml.jaxb.eml.TaxonomicCoverage.TaxonomicSystem createTaxonomicCoverageTaxonomicSystem() {
        return new au.org.ecoinformatics.eml.jaxb.eml.TaxonomicCoverage.TaxonomicSystem();
    }

    /**
     * Create an instance of {@link au.org.ecoinformatics.eml.jaxb.eml.TaxonomicCoverage.TaxonomicSystem.Vouchers }
     * 
     */
    public au.org.ecoinformatics.eml.jaxb.eml.TaxonomicCoverage.TaxonomicSystem.Vouchers createTaxonomicCoverageTaxonomicSystemVouchers() {
        return new au.org.ecoinformatics.eml.jaxb.eml.TaxonomicCoverage.TaxonomicSystem.Vouchers();
    }

    /**
     * Create an instance of {@link Coverage }
     * 
     */
    public Coverage createCoverage() {
        return new Coverage();
    }

    /**
     * Create an instance of {@link I18NNonEmptyStringType }
     * 
     */
    public I18NNonEmptyStringType createI18NNonEmptyStringType() {
        return new I18NNonEmptyStringType();
    }

    /**
     * Create an instance of {@link ConnectionDefinitionType }
     * 
     */
    public ConnectionDefinitionType createConnectionDefinitionType() {
        return new ConnectionDefinitionType();
    }

    /**
     * Create an instance of {@link ConnectionType }
     * 
     */
    public ConnectionType createConnectionType() {
        return new ConnectionType();
    }

    /**
     * Create an instance of {@link MaintenanceType }
     * 
     */
    public MaintenanceType createMaintenanceType() {
        return new MaintenanceType();
    }

    /**
     * Create an instance of {@link ParagraphType }
     * 
     */
    public ParagraphType createParagraphType() {
        return new ParagraphType();
    }

    /**
     * Create an instance of {@link ListType }
     * 
     */
    public ListType createListType() {
        return new ListType();
    }

    /**
     * Create an instance of {@link Eml.AdditionalMetadata }
     * 
     */
    public Eml.AdditionalMetadata createEmlAdditionalMetadata() {
        return new Eml.AdditionalMetadata();
    }

    /**
     * Create an instance of {@link ProtocolType }
     * 
     */
    public ProtocolType createProtocolType() {
        return new ProtocolType();
    }

    /**
     * Create an instance of {@link ProtocolType.KeywordSet }
     * 
     */
    public ProtocolType.KeywordSet createProtocolTypeKeywordSet() {
        return new ProtocolType.KeywordSet();
    }

    /**
     * Create an instance of {@link SoftwareType }
     * 
     */
    public SoftwareType createSoftwareType() {
        return new SoftwareType();
    }

    /**
     * Create an instance of {@link SoftwareType.Implementation }
     * 
     */
    public SoftwareType.Implementation createSoftwareTypeImplementation() {
        return new SoftwareType.Implementation();
    }

    /**
     * Create an instance of {@link AccessType }
     * 
     */
    public AccessType createAccessType() {
        return new AccessType();
    }

    /**
     * Create an instance of {@link DatasetType }
     * 
     */
    public DatasetType createDatasetType() {
        return new DatasetType();
    }

    /**
     * Create an instance of {@link CitationType }
     * 
     */
    public CitationType createCitationType() {
        return new CitationType();
    }

    /**
     * Create an instance of {@link TextType }
     * 
     */
    public TextType createTextType() {
        return new TextType();
    }

    /**
     * Create an instance of {@link ModuleDocs }
     * 
     */
    public ModuleDocs createModuleDocs() {
        return new ModuleDocs();
    }

    /**
     * Create an instance of {@link SubSuperScriptType }
     * 
     */
    public SubSuperScriptType createSubSuperScriptType() {
        return new SubSuperScriptType();
    }

    /**
     * Create an instance of {@link I18NString }
     * 
     */
    public I18NString createI18NString() {
        return new I18NString();
    }

    /**
     * Create an instance of {@link SectionType }
     * 
     */
    public SectionType createSectionType() {
        return new SectionType();
    }

    /**
     * Create an instance of {@link UrlType }
     * 
     */
    public UrlType createUrlType() {
        return new UrlType();
    }

    /**
     * Create an instance of {@link InlineType }
     * 
     */
    public InlineType createInlineType() {
        return new InlineType();
    }

    /**
     * Create an instance of {@link DistributionType }
     * 
     */
    public DistributionType createDistributionType() {
        return new DistributionType();
    }

    /**
     * Create an instance of {@link OfflineType }
     * 
     */
    public OfflineType createOfflineType() {
        return new OfflineType();
    }

    /**
     * Create an instance of {@link OnlineType }
     * 
     */
    public OnlineType createOnlineType() {
        return new OnlineType();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link Person }
     * 
     */
    public Person createPerson() {
        return new Person();
    }

    /**
     * Create an instance of {@link TaxonomicClassificationType }
     * 
     */
    public TaxonomicClassificationType createTaxonomicClassificationType() {
        return new TaxonomicClassificationType();
    }

    /**
     * Create an instance of {@link GRingPointType }
     * 
     */
    public GRingPointType createGRingPointType() {
        return new GRingPointType();
    }

    /**
     * Create an instance of {@link Book }
     * 
     */
    public Book createBook() {
        return new Book();
    }

    /**
     * Create an instance of {@link Map }
     * 
     */
    public Map createMap() {
        return new Map();
    }

    /**
     * Create an instance of {@link Report }
     * 
     */
    public Report createReport() {
        return new Report();
    }

    /**
     * Create an instance of {@link ConferenceProceedings }
     * 
     */
    public ConferenceProceedings createConferenceProceedings() {
        return new ConferenceProceedings();
    }

    /**
     * Create an instance of {@link Manuscript }
     * 
     */
    public Manuscript createManuscript() {
        return new Manuscript();
    }

    /**
     * Create an instance of {@link Article }
     * 
     */
    public Article createArticle() {
        return new Article();
    }

    /**
     * Create an instance of {@link Thesis }
     * 
     */
    public Thesis createThesis() {
        return new Thesis();
    }

    /**
     * Create an instance of {@link Chapter }
     * 
     */
    public Chapter createChapter() {
        return new Chapter();
    }

    /**
     * Create an instance of {@link Presentation }
     * 
     */
    public Presentation createPresentation() {
        return new Presentation();
    }

    /**
     * Create an instance of {@link AudioVisual }
     * 
     */
    public AudioVisual createAudioVisual() {
        return new AudioVisual();
    }

    /**
     * Create an instance of {@link Generic }
     * 
     */
    public Generic createGeneric() {
        return new Generic();
    }

    /**
     * Create an instance of {@link PersonalCommunication }
     * 
     */
    public PersonalCommunication createPersonalCommunication() {
        return new PersonalCommunication();
    }

    /**
     * Create an instance of {@link AccessRule }
     * 
     */
    public AccessRule createAccessRule() {
        return new AccessRule();
    }

    /**
     * Create an instance of {@link OtherEntityType }
     * 
     */
    public OtherEntityType createOtherEntityType() {
        return new OtherEntityType();
    }

    /**
     * Create an instance of {@link PhysicalOnlineType }
     * 
     */
    public PhysicalOnlineType createPhysicalOnlineType() {
        return new PhysicalOnlineType();
    }

    /**
     * Create an instance of {@link PhysicalDistributionType }
     * 
     */
    public PhysicalDistributionType createPhysicalDistributionType() {
        return new PhysicalDistributionType();
    }

    /**
     * Create an instance of {@link ProcedureStepType }
     * 
     */
    public ProcedureStepType createProcedureStepType() {
        return new ProcedureStepType();
    }

    /**
     * Create an instance of {@link Dependency }
     * 
     */
    public Dependency createDependency() {
        return new Dependency();
    }

    /**
     * Create an instance of {@link AttributeListType }
     * 
     */
    public AttributeListType createAttributeListType() {
        return new AttributeListType();
    }

    /**
     * Create an instance of {@link PrecisionType }
     * 
     */
    public PrecisionType createPrecisionType() {
        return new PrecisionType();
    }

    /**
     * Create an instance of {@link UnitType }
     * 
     */
    public UnitType createUnitType() {
        return new UnitType();
    }

    /**
     * Create an instance of {@link DataTableType }
     * 
     */
    public DataTableType createDataTableType() {
        return new DataTableType();
    }

    /**
     * Create an instance of {@link BandType }
     * 
     */
    public BandType createBandType() {
        return new BandType();
    }

    /**
     * Create an instance of {@link ProjectionList }
     * 
     */
    public ProjectionList createProjectionList() {
        return new ProjectionList();
    }

    /**
     * Create an instance of {@link SpatialVectorType }
     * 
     */
    public SpatialVectorType createSpatialVectorType() {
        return new SpatialVectorType();
    }

    /**
     * Create an instance of {@link StoredProcedureType }
     * 
     */
    public StoredProcedureType createStoredProcedureType() {
        return new StoredProcedureType();
    }

    /**
     * Create an instance of {@link ParameterType }
     * 
     */
    public ParameterType createParameterType() {
        return new ParameterType();
    }

    /**
     * Create an instance of {@link ViewType.AlternateIdentifier }
     * 
     */
    public ViewType.AlternateIdentifier createViewTypeAlternateIdentifier() {
        return new ViewType.AlternateIdentifier();
    }

    /**
     * Create an instance of {@link ViewType.References }
     * 
     */
    public ViewType.References createViewTypeReferences() {
        return new ViewType.References();
    }

    /**
     * Create an instance of {@link VectorDataQuality.QuantitativeAccuracyReport }
     * 
     */
    public VectorDataQuality.QuantitativeAccuracyReport createVectorDataQualityQuantitativeAccuracyReport() {
        return new VectorDataQuality.QuantitativeAccuracyReport();
    }

    /**
     * Create an instance of {@link GeogCoordSysType.Datum }
     * 
     */
    public GeogCoordSysType.Datum createGeogCoordSysTypeDatum() {
        return new GeogCoordSysType.Datum();
    }

    /**
     * Create an instance of {@link GeogCoordSysType.Spheroid }
     * 
     */
    public GeogCoordSysType.Spheroid createGeogCoordSysTypeSpheroid() {
        return new GeogCoordSysType.Spheroid();
    }

    /**
     * Create an instance of {@link GeogCoordSysType.PrimeMeridian }
     * 
     */
    public GeogCoordSysType.PrimeMeridian createGeogCoordSysTypePrimeMeridian() {
        return new GeogCoordSysType.PrimeMeridian();
    }

    /**
     * Create an instance of {@link GeogCoordSysType.Unit }
     * 
     */
    public GeogCoordSysType.Unit createGeogCoordSysTypeUnit() {
        return new GeogCoordSysType.Unit();
    }

    /**
     * Create an instance of {@link SpatialReferenceType.VertCoordSys.AltitudeSysDef }
     * 
     */
    public SpatialReferenceType.VertCoordSys.AltitudeSysDef createSpatialReferenceTypeVertCoordSysAltitudeSysDef() {
        return new SpatialReferenceType.VertCoordSys.AltitudeSysDef();
    }

    /**
     * Create an instance of {@link SpatialReferenceType.VertCoordSys.DepthSysDef }
     * 
     */
    public SpatialReferenceType.VertCoordSys.DepthSysDef createSpatialReferenceTypeVertCoordSysDepthSysDef() {
        return new SpatialReferenceType.VertCoordSys.DepthSysDef();
    }

    /**
     * Create an instance of {@link HorizCoordSysType.ProjCoordSys.Projection.Parameter }
     * 
     */
    public HorizCoordSysType.ProjCoordSys.Projection.Parameter createHorizCoordSysTypeProjCoordSysProjectionParameter() {
        return new HorizCoordSysType.ProjCoordSys.Projection.Parameter();
    }

    /**
     * Create an instance of {@link HorizCoordSysType.ProjCoordSys.Projection.Unit }
     * 
     */
    public HorizCoordSysType.ProjCoordSys.Projection.Unit createHorizCoordSysTypeProjCoordSysProjectionUnit() {
        return new HorizCoordSysType.ProjCoordSys.Projection.Unit();
    }

    /**
     * Create an instance of {@link RasterDataQuality.QuantitativeAccuracyReport }
     * 
     */
    public RasterDataQuality.QuantitativeAccuracyReport createRasterDataQualityQuantitativeAccuracyReport() {
        return new RasterDataQuality.QuantitativeAccuracyReport();
    }

    /**
     * Create an instance of {@link SpatialRasterType.ImageDescription }
     * 
     */
    public SpatialRasterType.ImageDescription createSpatialRasterTypeImageDescription() {
        return new SpatialRasterType.ImageDescription();
    }

    /**
     * Create an instance of {@link SpatialRasterType.GeoreferenceInfo.CornerPoint }
     * 
     */
    public SpatialRasterType.GeoreferenceInfo.CornerPoint createSpatialRasterTypeGeoreferenceInfoCornerPoint() {
        return new SpatialRasterType.GeoreferenceInfo.CornerPoint();
    }

    /**
     * Create an instance of {@link SpatialRasterType.GeoreferenceInfo.ControlPoint }
     * 
     */
    public SpatialRasterType.GeoreferenceInfo.ControlPoint createSpatialRasterTypeGeoreferenceInfoControlPoint() {
        return new SpatialRasterType.GeoreferenceInfo.ControlPoint();
    }

    /**
     * Create an instance of {@link SpatialRasterType.GeoreferenceInfo.BilinearFit }
     * 
     */
    public SpatialRasterType.GeoreferenceInfo.BilinearFit createSpatialRasterTypeGeoreferenceInfoBilinearFit() {
        return new SpatialRasterType.GeoreferenceInfo.BilinearFit();
    }

    /**
     * Create an instance of {@link ConstraintType.CheckConstraint }
     * 
     */
    public ConstraintType.CheckConstraint createConstraintTypeCheckConstraint() {
        return new ConstraintType.CheckConstraint();
    }

    /**
     * Create an instance of {@link ConstraintType.ForeignKey }
     * 
     */
    public ConstraintType.ForeignKey createConstraintTypeForeignKey() {
        return new ConstraintType.ForeignKey();
    }

    /**
     * Create an instance of {@link ConstraintType.NotNullConstraint.Key }
     * 
     */
    public ConstraintType.NotNullConstraint.Key createConstraintTypeNotNullConstraintKey() {
        return new ConstraintType.NotNullConstraint.Key();
    }

    /**
     * Create an instance of {@link ConstraintType.JoinCondition.Key }
     * 
     */
    public ConstraintType.JoinCondition.Key createConstraintTypeJoinConditionKey() {
        return new ConstraintType.JoinCondition.Key();
    }

    /**
     * Create an instance of {@link ConstraintType.JoinCondition.Cardinality }
     * 
     */
    public ConstraintType.JoinCondition.Cardinality createConstraintTypeJoinConditionCardinality() {
        return new ConstraintType.JoinCondition.Cardinality();
    }

    /**
     * Create an instance of {@link ConstraintType.JoinCondition.ReferencedKey }
     * 
     */
    public ConstraintType.JoinCondition.ReferencedKey createConstraintTypeJoinConditionReferencedKey() {
        return new ConstraintType.JoinCondition.ReferencedKey();
    }

    /**
     * Create an instance of {@link ConstraintType.UniqueKey.Key }
     * 
     */
    public ConstraintType.UniqueKey.Key createConstraintTypeUniqueKeyKey() {
        return new ConstraintType.UniqueKey.Key();
    }

    /**
     * Create an instance of {@link ConstraintType.PrimaryKey.Key }
     * 
     */
    public ConstraintType.PrimaryKey.Key createConstraintTypePrimaryKeyKey() {
        return new ConstraintType.PrimaryKey.Key();
    }

    /**
     * Create an instance of {@link NumericDomainType.Bounds.Minimum }
     * 
     */
    public NumericDomainType.Bounds.Minimum createNumericDomainTypeBoundsMinimum() {
        return new NumericDomainType.Bounds.Minimum();
    }

    /**
     * Create an instance of {@link NumericDomainType.Bounds.Maximum }
     * 
     */
    public NumericDomainType.Bounds.Maximum createNumericDomainTypeBoundsMaximum() {
        return new NumericDomainType.Bounds.Maximum();
    }

    /**
     * Create an instance of {@link DateTimeDomainType.Bounds.Minimum }
     * 
     */
    public DateTimeDomainType.Bounds.Minimum createDateTimeDomainTypeBoundsMinimum() {
        return new DateTimeDomainType.Bounds.Minimum();
    }

    /**
     * Create an instance of {@link DateTimeDomainType.Bounds.Maximum }
     * 
     */
    public DateTimeDomainType.Bounds.Maximum createDateTimeDomainTypeBoundsMaximum() {
        return new DateTimeDomainType.Bounds.Maximum();
    }

    /**
     * Create an instance of {@link Accuracy.QuantitativeAttributeAccuracyAssessment }
     * 
     */
    public Accuracy.QuantitativeAttributeAccuracyAssessment createAccuracyQuantitativeAttributeAccuracyAssessment() {
        return new Accuracy.QuantitativeAttributeAccuracyAssessment();
    }

    /**
     * Create an instance of {@link NonNumericDomainType.TextDomain }
     * 
     */
    public NonNumericDomainType.TextDomain createNonNumericDomainTypeTextDomain() {
        return new NonNumericDomainType.TextDomain();
    }

    /**
     * Create an instance of {@link NonNumericDomainType.EnumeratedDomain.CodeDefinition }
     * 
     */
    public NonNumericDomainType.EnumeratedDomain.CodeDefinition createNonNumericDomainTypeEnumeratedDomainCodeDefinition() {
        return new NonNumericDomainType.EnumeratedDomain.CodeDefinition();
    }

    /**
     * Create an instance of {@link NonNumericDomainType.EnumeratedDomain.ExternalCodeSet }
     * 
     */
    public NonNumericDomainType.EnumeratedDomain.ExternalCodeSet createNonNumericDomainTypeEnumeratedDomainExternalCodeSet() {
        return new NonNumericDomainType.EnumeratedDomain.ExternalCodeSet();
    }

    /**
     * Create an instance of {@link NonNumericDomainType.EnumeratedDomain.EntityCodeList }
     * 
     */
    public NonNumericDomainType.EnumeratedDomain.EntityCodeList createNonNumericDomainTypeEnumeratedDomainEntityCodeList() {
        return new NonNumericDomainType.EnumeratedDomain.EntityCodeList();
    }

    /**
     * Create an instance of {@link AttributeType.StorageType }
     * 
     */
    public AttributeType.StorageType createAttributeTypeStorageType() {
        return new AttributeType.StorageType();
    }

    /**
     * Create an instance of {@link AttributeType.MissingValueCode }
     * 
     */
    public AttributeType.MissingValueCode createAttributeTypeMissingValueCode() {
        return new AttributeType.MissingValueCode();
    }

    /**
     * Create an instance of {@link AttributeType.MeasurementScale.Nominal }
     * 
     */
    public AttributeType.MeasurementScale.Nominal createAttributeTypeMeasurementScaleNominal() {
        return new AttributeType.MeasurementScale.Nominal();
    }

    /**
     * Create an instance of {@link AttributeType.MeasurementScale.Ordinal }
     * 
     */
    public AttributeType.MeasurementScale.Ordinal createAttributeTypeMeasurementScaleOrdinal() {
        return new AttributeType.MeasurementScale.Ordinal();
    }

    /**
     * Create an instance of {@link AttributeType.MeasurementScale.Interval }
     * 
     */
    public AttributeType.MeasurementScale.Interval createAttributeTypeMeasurementScaleInterval() {
        return new AttributeType.MeasurementScale.Interval();
    }

    /**
     * Create an instance of {@link AttributeType.MeasurementScale.Ratio }
     * 
     */
    public AttributeType.MeasurementScale.Ratio createAttributeTypeMeasurementScaleRatio() {
        return new AttributeType.MeasurementScale.Ratio();
    }

    /**
     * Create an instance of {@link AttributeType.MeasurementScale.DateTime }
     * 
     */
    public AttributeType.MeasurementScale.DateTime createAttributeTypeMeasurementScaleDateTime() {
        return new AttributeType.MeasurementScale.DateTime();
    }

    /**
     * Create an instance of {@link MethodsType.MethodStep }
     * 
     */
    public MethodsType.MethodStep createMethodsTypeMethodStep() {
        return new MethodsType.MethodStep();
    }

    /**
     * Create an instance of {@link MethodsType.Sampling.StudyExtent }
     * 
     */
    public MethodsType.Sampling.StudyExtent createMethodsTypeSamplingStudyExtent() {
        return new MethodsType.Sampling.StudyExtent();
    }

    /**
     * Create an instance of {@link MethodsType.Sampling.SpatialSamplingUnits }
     * 
     */
    public MethodsType.Sampling.SpatialSamplingUnits createMethodsTypeSamplingSpatialSamplingUnits() {
        return new MethodsType.Sampling.SpatialSamplingUnits();
    }

    /**
     * Create an instance of {@link PhysicalType.Size }
     * 
     */
    public PhysicalType.Size createPhysicalTypeSize() {
        return new PhysicalType.Size();
    }

    /**
     * Create an instance of {@link PhysicalType.Authentication }
     * 
     */
    public PhysicalType.Authentication createPhysicalTypeAuthentication() {
        return new PhysicalType.Authentication();
    }

    /**
     * Create an instance of {@link PhysicalType.DataFormat.ExternallyDefinedFormat }
     * 
     */
    public PhysicalType.DataFormat.ExternallyDefinedFormat createPhysicalTypeDataFormatExternallyDefinedFormat() {
        return new PhysicalType.DataFormat.ExternallyDefinedFormat();
    }

    /**
     * Create an instance of {@link PhysicalType.DataFormat.BinaryRasterFormat.MultiBand }
     * 
     */
    public PhysicalType.DataFormat.BinaryRasterFormat.MultiBand createPhysicalTypeDataFormatBinaryRasterFormatMultiBand() {
        return new PhysicalType.DataFormat.BinaryRasterFormat.MultiBand();
    }

    /**
     * Create an instance of {@link PhysicalType.DataFormat.TextFormat.SimpleDelimited }
     * 
     */
    public PhysicalType.DataFormat.TextFormat.SimpleDelimited createPhysicalTypeDataFormatTextFormatSimpleDelimited() {
        return new PhysicalType.DataFormat.TextFormat.SimpleDelimited();
    }

    /**
     * Create an instance of {@link PhysicalType.DataFormat.TextFormat.Complex.TextFixed }
     * 
     */
    public PhysicalType.DataFormat.TextFormat.Complex.TextFixed createPhysicalTypeDataFormatTextFormatComplexTextFixed() {
        return new PhysicalType.DataFormat.TextFormat.Complex.TextFixed();
    }

    /**
     * Create an instance of {@link PhysicalType.DataFormat.TextFormat.Complex.TextDelimited }
     * 
     */
    public PhysicalType.DataFormat.TextFormat.Complex.TextDelimited createPhysicalTypeDataFormatTextFormatComplexTextDelimited() {
        return new PhysicalType.DataFormat.TextFormat.Complex.TextDelimited();
    }

    /**
     * Create an instance of {@link ResearchProjectType.Personnel }
     * 
     */
    public ResearchProjectType.Personnel createResearchProjectTypePersonnel() {
        return new ResearchProjectType.Personnel();
    }

    /**
     * Create an instance of {@link ResearchProjectType.DesignDescription }
     * 
     */
    public ResearchProjectType.DesignDescription createResearchProjectTypeDesignDescription() {
        return new ResearchProjectType.DesignDescription();
    }

    /**
     * Create an instance of {@link ResearchProjectType.StudyAreaDescription.Descriptor.DescriptorValue }
     * 
     */
    public ResearchProjectType.StudyAreaDescription.Descriptor.DescriptorValue createResearchProjectTypeStudyAreaDescriptionDescriptorDescriptorValue() {
        return new ResearchProjectType.StudyAreaDescription.Descriptor.DescriptorValue();
    }

    /**
     * Create an instance of {@link ResponsibleParty.Phone }
     * 
     */
    public ResponsibleParty.Phone createResponsiblePartyPhone() {
        return new ResponsibleParty.Phone();
    }

    /**
     * Create an instance of {@link ResponsibleParty.UserId }
     * 
     */
    public ResponsibleParty.UserId createResponsiblePartyUserId() {
        return new ResponsibleParty.UserId();
    }

    /**
     * Create an instance of {@link au.org.ecoinformatics.eml.jaxb.eml.TemporalCoverage.RangeOfDates }
     * 
     */
    public au.org.ecoinformatics.eml.jaxb.eml.TemporalCoverage.RangeOfDates createTemporalCoverageRangeOfDates() {
        return new au.org.ecoinformatics.eml.jaxb.eml.TemporalCoverage.RangeOfDates();
    }

    /**
     * Create an instance of {@link SingleDateTimeType.AlternativeTimeScale }
     * 
     */
    public SingleDateTimeType.AlternativeTimeScale createSingleDateTimeTypeAlternativeTimeScale() {
        return new SingleDateTimeType.AlternativeTimeScale();
    }

    /**
     * Create an instance of {@link GeographicCoverage.DatasetGPolygon.DatasetGPolygonOuterGRing }
     * 
     */
    public GeographicCoverage.DatasetGPolygon.DatasetGPolygonOuterGRing createGeographicCoverageDatasetGPolygonDatasetGPolygonOuterGRing() {
        return new GeographicCoverage.DatasetGPolygon.DatasetGPolygonOuterGRing();
    }

    /**
     * Create an instance of {@link GeographicCoverage.DatasetGPolygon.DatasetGPolygonExclusionGRing }
     * 
     */
    public GeographicCoverage.DatasetGPolygon.DatasetGPolygonExclusionGRing createGeographicCoverageDatasetGPolygonDatasetGPolygonExclusionGRing() {
        return new GeographicCoverage.DatasetGPolygon.DatasetGPolygonExclusionGRing();
    }

    /**
     * Create an instance of {@link GeographicCoverage.BoundingCoordinates.BoundingAltitudes }
     * 
     */
    public GeographicCoverage.BoundingCoordinates.BoundingAltitudes createGeographicCoverageBoundingCoordinatesBoundingAltitudes() {
        return new GeographicCoverage.BoundingCoordinates.BoundingAltitudes();
    }

    /**
     * Create an instance of {@link au.org.ecoinformatics.eml.jaxb.eml.TaxonomicCoverage.TaxonomicSystem.ClassificationSystem }
     * 
     */
    public au.org.ecoinformatics.eml.jaxb.eml.TaxonomicCoverage.TaxonomicSystem.ClassificationSystem createTaxonomicCoverageTaxonomicSystemClassificationSystem() {
        return new au.org.ecoinformatics.eml.jaxb.eml.TaxonomicCoverage.TaxonomicSystem.ClassificationSystem();
    }

    /**
     * Create an instance of {@link au.org.ecoinformatics.eml.jaxb.eml.TaxonomicCoverage.TaxonomicSystem.Vouchers.Repository }
     * 
     */
    public au.org.ecoinformatics.eml.jaxb.eml.TaxonomicCoverage.TaxonomicSystem.Vouchers.Repository createTaxonomicCoverageTaxonomicSystemVouchersRepository() {
        return new au.org.ecoinformatics.eml.jaxb.eml.TaxonomicCoverage.TaxonomicSystem.Vouchers.Repository();
    }

    /**
     * Create an instance of {@link Coverage.TemporalCoverage }
     * 
     */
    public Coverage.TemporalCoverage createCoverageTemporalCoverage() {
        return new Coverage.TemporalCoverage();
    }

    /**
     * Create an instance of {@link Coverage.TaxonomicCoverage }
     * 
     */
    public Coverage.TaxonomicCoverage createCoverageTaxonomicCoverage() {
        return new Coverage.TaxonomicCoverage();
    }

    /**
     * Create an instance of {@link I18NNonEmptyStringType.Value }
     * 
     */
    public I18NNonEmptyStringType.Value createI18NNonEmptyStringTypeValue() {
        return new I18NNonEmptyStringType.Value();
    }

    /**
     * Create an instance of {@link ConnectionDefinitionType.SchemeName }
     * 
     */
    public ConnectionDefinitionType.SchemeName createConnectionDefinitionTypeSchemeName() {
        return new ConnectionDefinitionType.SchemeName();
    }

    /**
     * Create an instance of {@link ConnectionDefinitionType.ParameterDefinition }
     * 
     */
    public ConnectionDefinitionType.ParameterDefinition createConnectionDefinitionTypeParameterDefinition() {
        return new ConnectionDefinitionType.ParameterDefinition();
    }

    /**
     * Create an instance of {@link ConnectionType.Parameter }
     * 
     */
    public ConnectionType.Parameter createConnectionTypeParameter() {
        return new ConnectionType.Parameter();
    }

    /**
     * Create an instance of {@link MaintenanceType.ChangeHistory }
     * 
     */
    public MaintenanceType.ChangeHistory createMaintenanceTypeChangeHistory() {
        return new MaintenanceType.ChangeHistory();
    }

    /**
     * Create an instance of {@link ParagraphType.Emphasis }
     * 
     */
    public ParagraphType.Emphasis createParagraphTypeEmphasis() {
        return new ParagraphType.Emphasis();
    }

    /**
     * Create an instance of {@link ParagraphType.LiteralLayout }
     * 
     */
    public ParagraphType.LiteralLayout createParagraphTypeLiteralLayout() {
        return new ParagraphType.LiteralLayout();
    }

    /**
     * Create an instance of {@link ParagraphType.Ulink }
     * 
     */
    public ParagraphType.Ulink createParagraphTypeUlink() {
        return new ParagraphType.Ulink();
    }

    /**
     * Create an instance of {@link ListType.Listitem }
     * 
     */
    public ListType.Listitem createListTypeListitem() {
        return new ListType.Listitem();
    }

    /**
     * Create an instance of {@link Eml.AdditionalMetadata.Metadata }
     * 
     */
    public Eml.AdditionalMetadata.Metadata createEmlAdditionalMetadataMetadata() {
        return new Eml.AdditionalMetadata.Metadata();
    }

    /**
     * Create an instance of {@link ProtocolType.AlternateIdentifier }
     * 
     */
    public ProtocolType.AlternateIdentifier createProtocolTypeAlternateIdentifier() {
        return new ProtocolType.AlternateIdentifier();
    }

    /**
     * Create an instance of {@link ProtocolType.AssociatedParty }
     * 
     */
    public ProtocolType.AssociatedParty createProtocolTypeAssociatedParty() {
        return new ProtocolType.AssociatedParty();
    }

    /**
     * Create an instance of {@link ProtocolType.KeywordSet.Keyword }
     * 
     */
    public ProtocolType.KeywordSet.Keyword createProtocolTypeKeywordSetKeyword() {
        return new ProtocolType.KeywordSet.Keyword();
    }

    /**
     * Create an instance of {@link SoftwareType.Implementation.Language }
     * 
     */
    public SoftwareType.Implementation.Language createSoftwareTypeImplementationLanguage() {
        return new SoftwareType.Implementation.Language();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "eml://ecoinformatics.org/documentation-2.1.1", name = "tooltip")
    public JAXBElement<String> createTooltip(String value) {
        return new JAXBElement<String>(_Tooltip_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataTableType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "eml://ecoinformatics.org/dataTable-2.1.1", name = "dataTable")
    public JAXBElement<DataTableType> createDataTable(DataTableType value) {
        return new JAXBElement<DataTableType>(_DataTable_QNAME, DataTableType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OtherEntityType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "eml://ecoinformatics.org/entity-2.1.1", name = "otherEntity")
    public JAXBElement<OtherEntityType> createOtherEntity(OtherEntityType value) {
        return new JAXBElement<OtherEntityType>(_OtherEntity_QNAME, OtherEntityType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SpatialVectorType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "eml://ecoinformatics.org/spatialVector-2.1.1", name = "spatialVector")
    public JAXBElement<SpatialVectorType> createSpatialVector(SpatialVectorType value) {
        return new JAXBElement<SpatialVectorType>(_SpatialVector_QNAME, SpatialVectorType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "eml://ecoinformatics.org/documentation-2.1.1", name = "example")
    public JAXBElement<TextType> createExample(TextType value) {
        return new JAXBElement<TextType>(_Example_QNAME, TextType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SpatialRasterType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "eml://ecoinformatics.org/spatialRaster-2.1.1", name = "spatialRaster")
    public JAXBElement<SpatialRasterType> createSpatialRaster(SpatialRasterType value) {
        return new JAXBElement<SpatialRasterType>(_SpatialRaster_QNAME, SpatialRasterType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "eml://ecoinformatics.org/text-2.1.1", name = "text")
    public JAXBElement<TextType> createText(TextType value) {
        return new JAXBElement<TextType>(_Text_QNAME, TextType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "eml://ecoinformatics.org/documentation-2.1.1", name = "description")
    public JAXBElement<TextType> createDescription(TextType value) {
        return new JAXBElement<TextType>(_Description_QNAME, TextType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MethodsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "eml://ecoinformatics.org/methods-2.1.1", name = "methods")
    public JAXBElement<MethodsType> createMethods(MethodsType value) {
        return new JAXBElement<MethodsType>(_Methods_QNAME, MethodsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResponsibleParty }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "eml://ecoinformatics.org/party-2.1.1", name = "party")
    public JAXBElement<ResponsibleParty> createParty(ResponsibleParty value) {
        return new JAXBElement<ResponsibleParty>(_Party_QNAME, ResponsibleParty.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "eml://ecoinformatics.org/attribute-2.1.1", name = "attribute")
    public JAXBElement<AttributeType> createAttribute(AttributeType value) {
        return new JAXBElement<AttributeType>(_Attribute_QNAME, AttributeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProtocolType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "eml://ecoinformatics.org/protocol-2.1.1", name = "protocol")
    public JAXBElement<ProtocolType> createProtocol(ProtocolType value) {
        return new JAXBElement<ProtocolType>(_Protocol_QNAME, ProtocolType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CitationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "eml://ecoinformatics.org/literature-2.1.1", name = "citation")
    public JAXBElement<CitationType> createCitation(CitationType value) {
        return new JAXBElement<CitationType>(_Citation_QNAME, CitationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AccessType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "eml://ecoinformatics.org/access-2.1.1", name = "access")
    public JAXBElement<AccessType> createAccess(AccessType value) {
        return new JAXBElement<AccessType>(_Access_QNAME, AccessType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "eml://ecoinformatics.org/attribute-2.1.1", name = "attributeList")
    public JAXBElement<AttributeListType> createAttributeList(AttributeListType value) {
        return new JAXBElement<AttributeListType>(_AttributeList_QNAME, AttributeListType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SpatialReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "eml://ecoinformatics.org/spatialReference-2.1.1", name = "spatialReference")
    public JAXBElement<SpatialReferenceType> createSpatialReference(SpatialReferenceType value) {
        return new JAXBElement<SpatialReferenceType>(_SpatialReference_QNAME, SpatialReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ViewType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "eml://ecoinformatics.org/view-2.1.1", name = "view")
    public JAXBElement<ViewType> createView(ViewType value) {
        return new JAXBElement<ViewType>(_View_QNAME, ViewType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DatasetType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "eml://ecoinformatics.org/dataset-2.1.1", name = "dataset")
    public JAXBElement<DatasetType> createDataset(DatasetType value) {
        return new JAXBElement<DatasetType>(_Dataset_QNAME, DatasetType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResearchProjectType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "eml://ecoinformatics.org/project-2.1.1", name = "researchProject")
    public JAXBElement<ResearchProjectType> createResearchProject(ResearchProjectType value) {
        return new JAXBElement<ResearchProjectType>(_ResearchProject_QNAME, ResearchProjectType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StoredProcedureType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "eml://ecoinformatics.org/storedProcedure-2.1.1", name = "storedProcedure")
    public JAXBElement<StoredProcedureType> createStoredProcedure(StoredProcedureType value) {
        return new JAXBElement<StoredProcedureType>(_StoredProcedure_QNAME, StoredProcedureType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "eml://ecoinformatics.org/documentation-2.1.1", name = "lineage")
    public JAXBElement<String> createLineage(String value) {
        return new JAXBElement<String>(_Lineage_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SoftwareType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "eml://ecoinformatics.org/software-2.1.1", name = "software")
    public JAXBElement<SoftwareType> createSoftware(SoftwareType value) {
        return new JAXBElement<SoftwareType>(_Software_QNAME, SoftwareType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "eml://ecoinformatics.org/documentation-2.1.1", name = "module")
    public JAXBElement<String> createModule(String value) {
        return new JAXBElement<String>(_Module_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PhysicalType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "eml://ecoinformatics.org/physical-2.1.1", name = "physical")
    public JAXBElement<PhysicalType> createPhysical(PhysicalType value) {
        return new JAXBElement<PhysicalType>(_Physical_QNAME, PhysicalType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "eml://ecoinformatics.org/documentation-2.1.1", name = "summary")
    public JAXBElement<String> createSummary(String value) {
        return new JAXBElement<String>(_Summary_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "licenseURL", scope = SoftwareType.class)
    public JAXBElement<String> createSoftwareTypeLicenseURL(String value) {
        return new JAXBElement<String>(_SoftwareTypeLicenseURL_QNAME, String.class, SoftwareType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "license", scope = SoftwareType.class)
    public JAXBElement<String> createSoftwareTypeLicense(String value) {
        return new JAXBElement<String>(_SoftwareTypeLicense_QNAME, String.class, SoftwareType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link I18NNonEmptyStringType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "organizationName", scope = ResponsibleParty.class)
    public JAXBElement<I18NNonEmptyStringType> createResponsiblePartyOrganizationName(I18NNonEmptyStringType value) {
        return new JAXBElement<I18NNonEmptyStringType>(_ResponsiblePartyOrganizationName_QNAME, I18NNonEmptyStringType.class, ResponsibleParty.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Person }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "individualName", scope = ResponsibleParty.class)
    public JAXBElement<Person> createResponsiblePartyIndividualName(Person value) {
        return new JAXBElement<Person>(_ResponsiblePartyIndividualName_QNAME, Person.class, ResponsibleParty.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link I18NNonEmptyStringType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "positionName", scope = ResponsibleParty.class)
    public JAXBElement<I18NNonEmptyStringType> createResponsiblePartyPositionName(I18NNonEmptyStringType value) {
        return new JAXBElement<I18NNonEmptyStringType>(_ResponsiblePartyPositionName_QNAME, I18NNonEmptyStringType.class, ResponsibleParty.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AccessRule }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "allow", scope = AccessType.class)
    public JAXBElement<AccessRule> createAccessTypeAllow(AccessRule value) {
        return new JAXBElement<AccessRule>(_AccessTypeAllow_QNAME, AccessRule.class, AccessType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AccessRule }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "deny", scope = AccessType.class)
    public JAXBElement<AccessRule> createAccessTypeDeny(AccessRule value) {
        return new JAXBElement<AccessRule>(_AccessTypeDeny_QNAME, AccessRule.class, AccessType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link I18NString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "citetitle", scope = ParagraphType.Ulink.class)
    public JAXBElement<I18NString> createParagraphTypeUlinkCitetitle(I18NString value) {
        return new JAXBElement<I18NString>(_ParagraphTypeUlinkCitetitle_QNAME, I18NString.class, ParagraphType.Ulink.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link I18NString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "value", scope = ParagraphType.LiteralLayout.class)
    public JAXBElement<I18NString> createParagraphTypeLiteralLayoutValue(I18NString value) {
        return new JAXBElement<I18NString>(_ParagraphTypeLiteralLayoutValue_QNAME, I18NString.class, ParagraphType.LiteralLayout.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ParagraphType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "para", scope = TextType.class)
    public JAXBElement<ParagraphType> createTextTypePara(ParagraphType value) {
        return new JAXBElement<ParagraphType>(_TextTypePara_QNAME, ParagraphType.class, TextType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "section", scope = TextType.class)
    public JAXBElement<SectionType> createTextTypeSection(SectionType value) {
        return new JAXBElement<SectionType>(_TextTypeSection_QNAME, SectionType.class, TextType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ParagraphType.LiteralLayout }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "literalLayout", scope = ParagraphType.class)
    public JAXBElement<ParagraphType.LiteralLayout> createParagraphTypeLiteralLayout(ParagraphType.LiteralLayout value) {
        return new JAXBElement<ParagraphType.LiteralLayout>(_ParagraphTypeLiteralLayout_QNAME, ParagraphType.LiteralLayout.class, ParagraphType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SubSuperScriptType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "superscript", scope = ParagraphType.class)
    public JAXBElement<SubSuperScriptType> createParagraphTypeSuperscript(SubSuperScriptType value) {
        return new JAXBElement<SubSuperScriptType>(_ParagraphTypeSuperscript_QNAME, SubSuperScriptType.class, ParagraphType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SubSuperScriptType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "subscript", scope = ParagraphType.class)
    public JAXBElement<SubSuperScriptType> createParagraphTypeSubscript(SubSuperScriptType value) {
        return new JAXBElement<SubSuperScriptType>(_ParagraphTypeSubscript_QNAME, SubSuperScriptType.class, ParagraphType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ParagraphType.Ulink }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ulink", scope = ParagraphType.class)
    public JAXBElement<ParagraphType.Ulink> createParagraphTypeUlink(ParagraphType.Ulink value) {
        return new JAXBElement<ParagraphType.Ulink>(_ParagraphTypeUlink_QNAME, ParagraphType.Ulink.class, ParagraphType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ParagraphType.Emphasis }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "emphasis", scope = ParagraphType.class)
    public JAXBElement<ParagraphType.Emphasis> createParagraphTypeEmphasis(ParagraphType.Emphasis value) {
        return new JAXBElement<ParagraphType.Emphasis>(_ParagraphTypeEmphasis_QNAME, ParagraphType.Emphasis.class, ParagraphType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link I18NString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "value", scope = ParagraphType.class)
    public JAXBElement<I18NString> createParagraphTypeValue(I18NString value) {
        return new JAXBElement<I18NString>(_ParagraphTypeLiteralLayoutValue_QNAME, I18NString.class, ParagraphType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "itemizedlist", scope = ParagraphType.class)
    public JAXBElement<ListType> createParagraphTypeItemizedlist(ListType value) {
        return new JAXBElement<ListType>(_ParagraphTypeItemizedlist_QNAME, ListType.class, ParagraphType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "orderedlist", scope = ParagraphType.class)
    public JAXBElement<ListType> createParagraphTypeOrderedlist(ListType value) {
        return new JAXBElement<ListType>(_ParagraphTypeOrderedlist_QNAME, ListType.class, ParagraphType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link I18NNonEmptyStringType.Value }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "value", scope = I18NNonEmptyStringType.class)
    public JAXBElement<I18NNonEmptyStringType.Value> createI18NNonEmptyStringTypeValue(I18NNonEmptyStringType.Value value) {
        return new JAXBElement<I18NNonEmptyStringType.Value>(_ParagraphTypeLiteralLayoutValue_QNAME, I18NNonEmptyStringType.Value.class, I18NNonEmptyStringType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "compressionMethod", scope = PhysicalType.class)
    public JAXBElement<String> createPhysicalTypeCompressionMethod(String value) {
        return new JAXBElement<String>(_PhysicalTypeCompressionMethod_QNAME, String.class, PhysicalType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "encodingMethod", scope = PhysicalType.class)
    public JAXBElement<String> createPhysicalTypeEncodingMethod(String value) {
        return new JAXBElement<String>(_PhysicalTypeEncodingMethod_QNAME, String.class, PhysicalType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SubSuperScriptType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "superscript", scope = SubSuperScriptType.class)
    public JAXBElement<SubSuperScriptType> createSubSuperScriptTypeSuperscript(SubSuperScriptType value) {
        return new JAXBElement<SubSuperScriptType>(_ParagraphTypeSuperscript_QNAME, SubSuperScriptType.class, SubSuperScriptType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SubSuperScriptType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "subscript", scope = SubSuperScriptType.class)
    public JAXBElement<SubSuperScriptType> createSubSuperScriptTypeSubscript(SubSuperScriptType value) {
        return new JAXBElement<SubSuperScriptType>(_ParagraphTypeSubscript_QNAME, SubSuperScriptType.class, SubSuperScriptType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link I18NString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "value", scope = SubSuperScriptType.class)
    public JAXBElement<I18NString> createSubSuperScriptTypeValue(I18NString value) {
        return new JAXBElement<I18NString>(_ParagraphTypeLiteralLayoutValue_QNAME, I18NString.class, SubSuperScriptType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "itemizedlist", scope = ListType.Listitem.class)
    public JAXBElement<ListType> createListTypeListitemItemizedlist(ListType value) {
        return new JAXBElement<ListType>(_ParagraphTypeItemizedlist_QNAME, ListType.class, ListType.Listitem.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ParagraphType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "para", scope = ListType.Listitem.class)
    public JAXBElement<ParagraphType> createListTypeListitemPara(ParagraphType value) {
        return new JAXBElement<ParagraphType>(_TextTypePara_QNAME, ParagraphType.class, ListType.Listitem.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "orderedlist", scope = ListType.Listitem.class)
    public JAXBElement<ListType> createListTypeListitemOrderedlist(ListType value) {
        return new JAXBElement<ListType>(_ParagraphTypeOrderedlist_QNAME, ListType.class, ListType.Listitem.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link I18NString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "value", scope = ParagraphType.Emphasis.class)
    public JAXBElement<I18NString> createParagraphTypeEmphasisValue(I18NString value) {
        return new JAXBElement<I18NString>(_ParagraphTypeLiteralLayoutValue_QNAME, I18NString.class, ParagraphType.Emphasis.class, value);
    }

}
