//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.02 at 04:58:44 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "eml://ecoinformatics.org/literature-2.1.1")
package au.org.ecoinformatics.eml.jaxb;
