//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.19 at 11:10:14 AM CST 
//


package au.org.ecoinformatics.eml.jaxb.sysmeta;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * An *ObjectLocationList* is the structure returned from
 *       the :func:`CNRead.resolve` method of the CN REST interface. It provides
 *       a list of locations from which the specified object can be retrieved.
 *       
 * 
 * <p>Java class for ObjectLocationList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ObjectLocationList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="identifier" type="{http://ns.dataone.org/service/types/v1}Identifier"/>
 *         &lt;element name="objectLocation" type="{http://ns.dataone.org/service/types/v1}ObjectLocation" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ObjectLocationList", propOrder = {
    "identifier",
    "objectLocations"
})
@XmlRootElement(name = "objectLocationList")
public class ObjectLocationList {

    @XmlElement(required = true)
    protected Identifier identifier;
    @XmlElement(name = "objectLocation")
    protected List<ObjectLocation> objectLocations;

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link Identifier }
     *     
     */
    public Identifier getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link Identifier }
     *     
     */
    public void setIdentifier(Identifier value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the objectLocations property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the objectLocations property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getObjectLocations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ObjectLocation }
     * 
     * 
     */
    public List<ObjectLocation> getObjectLocations() {
        if (objectLocations == null) {
            objectLocations = new ArrayList<ObjectLocation>();
        }
        return this.objectLocations;
    }

    public ObjectLocationList withIdentifier(Identifier value) {
        setIdentifier(value);
        return this;
    }

    public ObjectLocationList withObjectLocations(ObjectLocation... values) {
        if (values!= null) {
            for (ObjectLocation value: values) {
                getObjectLocations().add(value);
            }
        }
        return this;
    }

    public ObjectLocationList withObjectLocations(Collection<ObjectLocation> values) {
        if (values!= null) {
            getObjectLocations().addAll(values);
        }
        return this;
    }

}
