//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.23 at 04:26:08 PM CST 
//


package au.org.ecoinformatics.eml.jaxb.eml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for KeyTypeCode.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="KeyTypeCode">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="place"/>
 *     &lt;enumeration value="stratum"/>
 *     &lt;enumeration value="temporal"/>
 *     &lt;enumeration value="theme"/>
 *     &lt;enumeration value="taxonomic"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "KeyTypeCode", namespace = "eml://ecoinformatics.org/resource-2.1.1")
@XmlEnum
public enum KeyTypeCode {

    @XmlEnumValue("place")
    PLACE("place"),
    @XmlEnumValue("stratum")
    STRATUM("stratum"),
    @XmlEnumValue("temporal")
    TEMPORAL("temporal"),
    @XmlEnumValue("theme")
    THEME("theme"),
    @XmlEnumValue("taxonomic")
    TAXONOMIC("taxonomic");
    private final String value;

    KeyTypeCode(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static KeyTypeCode fromValue(String v) {
        for (KeyTypeCode c: KeyTypeCode.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
