//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.23 at 04:26:08 PM CST 
//


package au.org.ecoinformatics.eml.jaxb.eml;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Map complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Map">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="publisher" type="{eml://ecoinformatics.org/party-2.1.1}ResponsibleParty" minOccurs="0"/>
 *         &lt;element name="edition" type="{eml://ecoinformatics.org/resource-2.1.1}NonEmptyStringType" minOccurs="0"/>
 *         &lt;element name="geographicCoverage" type="{eml://ecoinformatics.org/coverage-2.1.1}GeographicCoverage" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="scale" type="{eml://ecoinformatics.org/resource-2.1.1}NonEmptyStringType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Map", propOrder = {
    "publisher",
    "edition",
    "geographicCoverage",
    "scale"
})
public class Map {

    protected ResponsibleParty publisher;
    protected String edition;
    protected List<GeographicCoverage> geographicCoverage;
    protected String scale;

    /**
     * Gets the value of the publisher property.
     * 
     * @return
     *     possible object is
     *     {@link ResponsibleParty }
     *     
     */
    public ResponsibleParty getPublisher() {
        return publisher;
    }

    /**
     * Sets the value of the publisher property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponsibleParty }
     *     
     */
    public void setPublisher(ResponsibleParty value) {
        this.publisher = value;
    }

    /**
     * Gets the value of the edition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEdition() {
        return edition;
    }

    /**
     * Sets the value of the edition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEdition(String value) {
        this.edition = value;
    }

    /**
     * Gets the value of the geographicCoverage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the geographicCoverage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGeographicCoverage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GeographicCoverage }
     * 
     * 
     */
    public List<GeographicCoverage> getGeographicCoverage() {
        if (geographicCoverage == null) {
            geographicCoverage = new ArrayList<GeographicCoverage>();
        }
        return this.geographicCoverage;
    }

    /**
     * Gets the value of the scale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScale() {
        return scale;
    }

    /**
     * Sets the value of the scale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScale(String value) {
        this.scale = value;
    }

    public Map withPublisher(ResponsibleParty value) {
        setPublisher(value);
        return this;
    }

    public Map withEdition(String value) {
        setEdition(value);
        return this;
    }

    public Map withGeographicCoverage(GeographicCoverage... values) {
        if (values!= null) {
            for (GeographicCoverage value: values) {
                getGeographicCoverage().add(value);
            }
        }
        return this;
    }

    public Map withGeographicCoverage(Collection<GeographicCoverage> values) {
        if (values!= null) {
            getGeographicCoverage().addAll(values);
        }
        return this;
    }

    public Map withScale(String value) {
        setScale(value);
        return this;
    }

}
