//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.19 at 11:10:18 AM CST 
//


package au.org.ecoinformatics.eml.jaxb.eml;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="horizCoordSysDef" type="{eml://ecoinformatics.org/spatialReference-2.1.1}horizCoordSysType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "horizCoordSysDef"
})
@XmlRootElement(name = "projectionList", namespace = "eml://ecoinformatics.org/spatialReference-2.1.1")
public class ProjectionList {

    @XmlElement(required = true)
    protected List<HorizCoordSysType> horizCoordSysDef;

    /**
     * Gets the value of the horizCoordSysDef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the horizCoordSysDef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHorizCoordSysDef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HorizCoordSysType }
     * 
     * 
     */
    public List<HorizCoordSysType> getHorizCoordSysDef() {
        if (horizCoordSysDef == null) {
            horizCoordSysDef = new ArrayList<HorizCoordSysType>();
        }
        return this.horizCoordSysDef;
    }

    public ProjectionList withHorizCoordSysDef(HorizCoordSysType... values) {
        if (values!= null) {
            for (HorizCoordSysType value: values) {
                getHorizCoordSysDef().add(value);
            }
        }
        return this;
    }

    public ProjectionList withHorizCoordSysDef(Collection<HorizCoordSysType> values) {
        if (values!= null) {
            getHorizCoordSysDef().addAll(values);
        }
        return this;
    }

}
