//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.23 at 04:26:08 PM CST 
//


package au.org.ecoinformatics.eml.jaxb.eml;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SpatialVectorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpatialVectorType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;sequence>
 *           &lt;group ref="{eml://ecoinformatics.org/entity-2.1.1}EntityGroup"/>
 *           &lt;element name="attributeList" type="{eml://ecoinformatics.org/attribute-2.1.1}AttributeListType"/>
 *           &lt;element name="constraint" type="{eml://ecoinformatics.org/constraint-2.1.1}ConstraintType" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="geometry" type="{eml://ecoinformatics.org/spatialVector-2.1.1}GeometryType" maxOccurs="unbounded"/>
 *           &lt;element name="geometricObjectCount" type="{eml://ecoinformatics.org/resource-2.1.1}NonEmptyStringType" minOccurs="0"/>
 *           &lt;element name="topologyLevel" type="{eml://ecoinformatics.org/spatialVector-2.1.1}TopologyLevel" minOccurs="0"/>
 *           &lt;element name="spatialReference" type="{eml://ecoinformatics.org/spatialReference-2.1.1}SpatialReferenceType" minOccurs="0"/>
 *           &lt;element name="horizontalAccuracy" type="{eml://ecoinformatics.org/spatialVector-2.1.1}DataQuality" minOccurs="0"/>
 *           &lt;element name="verticalAccuracy" type="{eml://ecoinformatics.org/spatialVector-2.1.1}DataQuality" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;group ref="{eml://ecoinformatics.org/resource-2.1.1}ReferencesGroup"/>
 *       &lt;/choice>
 *       &lt;attribute name="id" type="{eml://ecoinformatics.org/resource-2.1.1}IDType" />
 *       &lt;attribute name="system" type="{eml://ecoinformatics.org/resource-2.1.1}SystemType" />
 *       &lt;attribute name="scope" type="{eml://ecoinformatics.org/resource-2.1.1}ScopeType" default="document" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpatialVectorType", namespace = "eml://ecoinformatics.org/spatialVector-2.1.1", propOrder = {
    "alternateIdentifier",
    "entityName",
    "entityDescription",
    "physical",
    "coverage",
    "methods",
    "additionalInfo",
    "attributeList",
    "constraint",
    "geometry",
    "geometricObjectCount",
    "topologyLevel",
    "spatialReference",
    "horizontalAccuracy",
    "verticalAccuracy",
    "references"
})
public class SpatialVectorType {

    protected List<au.org.ecoinformatics.eml.jaxb.eml.ViewType.AlternateIdentifier> alternateIdentifier;
    protected String entityName;
    protected String entityDescription;
    protected List<PhysicalType> physical;
    protected Coverage coverage;
    protected MethodsType methods;
    protected List<TextType> additionalInfo;
    protected AttributeListType attributeList;
    protected List<ConstraintType> constraint;
    protected List<GeometryType> geometry;
    protected String geometricObjectCount;
    protected TopologyLevel topologyLevel;
    protected SpatialReferenceType spatialReference;
    protected VectorDataQuality horizontalAccuracy;
    protected VectorDataQuality verticalAccuracy;
    protected au.org.ecoinformatics.eml.jaxb.eml.ViewType.References references;
    @XmlAttribute(name = "id")
    protected List<String> id;
    @XmlAttribute(name = "system")
    protected List<String> system;
    @XmlAttribute(name = "scope")
    protected ScopeType scope;

    /**
     * Gets the value of the alternateIdentifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the alternateIdentifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAlternateIdentifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link au.org.ecoinformatics.eml.jaxb.eml.ViewType.AlternateIdentifier }
     * 
     * 
     */
    public List<au.org.ecoinformatics.eml.jaxb.eml.ViewType.AlternateIdentifier> getAlternateIdentifier() {
        if (alternateIdentifier == null) {
            alternateIdentifier = new ArrayList<au.org.ecoinformatics.eml.jaxb.eml.ViewType.AlternateIdentifier>();
        }
        return this.alternateIdentifier;
    }

    /**
     * Gets the value of the entityName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntityName() {
        return entityName;
    }

    /**
     * Sets the value of the entityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntityName(String value) {
        this.entityName = value;
    }

    /**
     * Gets the value of the entityDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntityDescription() {
        return entityDescription;
    }

    /**
     * Sets the value of the entityDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntityDescription(String value) {
        this.entityDescription = value;
    }

    /**
     * Gets the value of the physical property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the physical property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPhysical().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PhysicalType }
     * 
     * 
     */
    public List<PhysicalType> getPhysical() {
        if (physical == null) {
            physical = new ArrayList<PhysicalType>();
        }
        return this.physical;
    }

    /**
     * Gets the value of the coverage property.
     * 
     * @return
     *     possible object is
     *     {@link Coverage }
     *     
     */
    public Coverage getCoverage() {
        return coverage;
    }

    /**
     * Sets the value of the coverage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Coverage }
     *     
     */
    public void setCoverage(Coverage value) {
        this.coverage = value;
    }

    /**
     * Gets the value of the methods property.
     * 
     * @return
     *     possible object is
     *     {@link MethodsType }
     *     
     */
    public MethodsType getMethods() {
        return methods;
    }

    /**
     * Sets the value of the methods property.
     * 
     * @param value
     *     allowed object is
     *     {@link MethodsType }
     *     
     */
    public void setMethods(MethodsType value) {
        this.methods = value;
    }

    /**
     * Gets the value of the additionalInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionalInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionalInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getAdditionalInfo() {
        if (additionalInfo == null) {
            additionalInfo = new ArrayList<TextType>();
        }
        return this.additionalInfo;
    }

    /**
     * Gets the value of the attributeList property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeListType }
     *     
     */
    public AttributeListType getAttributeList() {
        return attributeList;
    }

    /**
     * Sets the value of the attributeList property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeListType }
     *     
     */
    public void setAttributeList(AttributeListType value) {
        this.attributeList = value;
    }

    /**
     * Gets the value of the constraint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the constraint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConstraint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConstraintType }
     * 
     * 
     */
    public List<ConstraintType> getConstraint() {
        if (constraint == null) {
            constraint = new ArrayList<ConstraintType>();
        }
        return this.constraint;
    }

    /**
     * Gets the value of the geometry property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the geometry property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGeometry().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GeometryType }
     * 
     * 
     */
    public List<GeometryType> getGeometry() {
        if (geometry == null) {
            geometry = new ArrayList<GeometryType>();
        }
        return this.geometry;
    }

    /**
     * Gets the value of the geometricObjectCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeometricObjectCount() {
        return geometricObjectCount;
    }

    /**
     * Sets the value of the geometricObjectCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeometricObjectCount(String value) {
        this.geometricObjectCount = value;
    }

    /**
     * Gets the value of the topologyLevel property.
     * 
     * @return
     *     possible object is
     *     {@link TopologyLevel }
     *     
     */
    public TopologyLevel getTopologyLevel() {
        return topologyLevel;
    }

    /**
     * Sets the value of the topologyLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link TopologyLevel }
     *     
     */
    public void setTopologyLevel(TopologyLevel value) {
        this.topologyLevel = value;
    }

    /**
     * Gets the value of the spatialReference property.
     * 
     * @return
     *     possible object is
     *     {@link SpatialReferenceType }
     *     
     */
    public SpatialReferenceType getSpatialReference() {
        return spatialReference;
    }

    /**
     * Sets the value of the spatialReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpatialReferenceType }
     *     
     */
    public void setSpatialReference(SpatialReferenceType value) {
        this.spatialReference = value;
    }

    /**
     * Gets the value of the horizontalAccuracy property.
     * 
     * @return
     *     possible object is
     *     {@link VectorDataQuality }
     *     
     */
    public VectorDataQuality getHorizontalAccuracy() {
        return horizontalAccuracy;
    }

    /**
     * Sets the value of the horizontalAccuracy property.
     * 
     * @param value
     *     allowed object is
     *     {@link VectorDataQuality }
     *     
     */
    public void setHorizontalAccuracy(VectorDataQuality value) {
        this.horizontalAccuracy = value;
    }

    /**
     * Gets the value of the verticalAccuracy property.
     * 
     * @return
     *     possible object is
     *     {@link VectorDataQuality }
     *     
     */
    public VectorDataQuality getVerticalAccuracy() {
        return verticalAccuracy;
    }

    /**
     * Sets the value of the verticalAccuracy property.
     * 
     * @param value
     *     allowed object is
     *     {@link VectorDataQuality }
     *     
     */
    public void setVerticalAccuracy(VectorDataQuality value) {
        this.verticalAccuracy = value;
    }

    /**
     * Gets the value of the references property.
     * 
     * @return
     *     possible object is
     *     {@link au.org.ecoinformatics.eml.jaxb.eml.ViewType.References }
     *     
     */
    public au.org.ecoinformatics.eml.jaxb.eml.ViewType.References getReferences() {
        return references;
    }

    /**
     * Sets the value of the references property.
     * 
     * @param value
     *     allowed object is
     *     {@link au.org.ecoinformatics.eml.jaxb.eml.ViewType.References }
     *     
     */
    public void setReferences(au.org.ecoinformatics.eml.jaxb.eml.ViewType.References value) {
        this.references = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the id property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getId() {
        if (id == null) {
            id = new ArrayList<String>();
        }
        return this.id;
    }

    /**
     * Gets the value of the system property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the system property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSystem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSystem() {
        if (system == null) {
            system = new ArrayList<String>();
        }
        return this.system;
    }

    /**
     * Gets the value of the scope property.
     * 
     * @return
     *     possible object is
     *     {@link ScopeType }
     *     
     */
    public ScopeType getScope() {
        if (scope == null) {
            return ScopeType.DOCUMENT;
        } else {
            return scope;
        }
    }

    /**
     * Sets the value of the scope property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScopeType }
     *     
     */
    public void setScope(ScopeType value) {
        this.scope = value;
    }

    public SpatialVectorType withAlternateIdentifier(au.org.ecoinformatics.eml.jaxb.eml.ViewType.AlternateIdentifier... values) {
        if (values!= null) {
            for (au.org.ecoinformatics.eml.jaxb.eml.ViewType.AlternateIdentifier value: values) {
                getAlternateIdentifier().add(value);
            }
        }
        return this;
    }

    public SpatialVectorType withAlternateIdentifier(Collection<au.org.ecoinformatics.eml.jaxb.eml.ViewType.AlternateIdentifier> values) {
        if (values!= null) {
            getAlternateIdentifier().addAll(values);
        }
        return this;
    }

    public SpatialVectorType withEntityName(String value) {
        setEntityName(value);
        return this;
    }

    public SpatialVectorType withEntityDescription(String value) {
        setEntityDescription(value);
        return this;
    }

    public SpatialVectorType withPhysical(PhysicalType... values) {
        if (values!= null) {
            for (PhysicalType value: values) {
                getPhysical().add(value);
            }
        }
        return this;
    }

    public SpatialVectorType withPhysical(Collection<PhysicalType> values) {
        if (values!= null) {
            getPhysical().addAll(values);
        }
        return this;
    }

    public SpatialVectorType withCoverage(Coverage value) {
        setCoverage(value);
        return this;
    }

    public SpatialVectorType withMethods(MethodsType value) {
        setMethods(value);
        return this;
    }

    public SpatialVectorType withAdditionalInfo(TextType... values) {
        if (values!= null) {
            for (TextType value: values) {
                getAdditionalInfo().add(value);
            }
        }
        return this;
    }

    public SpatialVectorType withAdditionalInfo(Collection<TextType> values) {
        if (values!= null) {
            getAdditionalInfo().addAll(values);
        }
        return this;
    }

    public SpatialVectorType withAttributeList(AttributeListType value) {
        setAttributeList(value);
        return this;
    }

    public SpatialVectorType withConstraint(ConstraintType... values) {
        if (values!= null) {
            for (ConstraintType value: values) {
                getConstraint().add(value);
            }
        }
        return this;
    }

    public SpatialVectorType withConstraint(Collection<ConstraintType> values) {
        if (values!= null) {
            getConstraint().addAll(values);
        }
        return this;
    }

    public SpatialVectorType withGeometry(GeometryType... values) {
        if (values!= null) {
            for (GeometryType value: values) {
                getGeometry().add(value);
            }
        }
        return this;
    }

    public SpatialVectorType withGeometry(Collection<GeometryType> values) {
        if (values!= null) {
            getGeometry().addAll(values);
        }
        return this;
    }

    public SpatialVectorType withGeometricObjectCount(String value) {
        setGeometricObjectCount(value);
        return this;
    }

    public SpatialVectorType withTopologyLevel(TopologyLevel value) {
        setTopologyLevel(value);
        return this;
    }

    public SpatialVectorType withSpatialReference(SpatialReferenceType value) {
        setSpatialReference(value);
        return this;
    }

    public SpatialVectorType withHorizontalAccuracy(VectorDataQuality value) {
        setHorizontalAccuracy(value);
        return this;
    }

    public SpatialVectorType withVerticalAccuracy(VectorDataQuality value) {
        setVerticalAccuracy(value);
        return this;
    }

    public SpatialVectorType withReferences(au.org.ecoinformatics.eml.jaxb.eml.ViewType.References value) {
        setReferences(value);
        return this;
    }

    public SpatialVectorType withId(String... values) {
        if (values!= null) {
            for (String value: values) {
                getId().add(value);
            }
        }
        return this;
    }

    public SpatialVectorType withId(Collection<String> values) {
        if (values!= null) {
            getId().addAll(values);
        }
        return this;
    }

    public SpatialVectorType withSystem(String... values) {
        if (values!= null) {
            for (String value: values) {
                getSystem().add(value);
            }
        }
        return this;
    }

    public SpatialVectorType withSystem(Collection<String> values) {
        if (values!= null) {
            getSystem().addAll(values);
        }
        return this;
    }

    public SpatialVectorType withScope(ScopeType value) {
        setScope(value);
        return this;
    }

}
