//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.03 at 05:40:36 PM CST 
//


package au.org.ecoinformatics.eml.jaxb.eml;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TemporalCoverage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TemporalCoverage">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;choice>
 *           &lt;element name="singleDateTime" type="{eml://ecoinformatics.org/coverage-2.1.1}SingleDateTimeType" maxOccurs="unbounded"/>
 *           &lt;element name="rangeOfDates">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="beginDate" type="{eml://ecoinformatics.org/coverage-2.1.1}SingleDateTimeType"/>
 *                     &lt;element name="endDate" type="{eml://ecoinformatics.org/coverage-2.1.1}SingleDateTimeType"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/choice>
 *         &lt;group ref="{eml://ecoinformatics.org/resource-2.1.1}ReferencesGroup"/>
 *       &lt;/choice>
 *       &lt;attribute name="id" type="{eml://ecoinformatics.org/resource-2.1.1}IDType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TemporalCoverage", namespace = "eml://ecoinformatics.org/coverage-2.1.1", propOrder = {
    "singleDateTime",
    "rangeOfDates",
    "references"
})
@XmlSeeAlso({
    au.org.ecoinformatics.eml.jaxb.eml.Coverage.TemporalCoverage.class
})
public class TemporalCoverage {

    protected List<SingleDateTimeType> singleDateTime;
    protected TemporalCoverage.RangeOfDates rangeOfDates;
    protected au.org.ecoinformatics.eml.jaxb.eml.ViewType.References references;
    @XmlAttribute(name = "id")
    protected List<String> id;

    /**
     * Gets the value of the singleDateTime property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the singleDateTime property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSingleDateTime().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SingleDateTimeType }
     * 
     * 
     */
    public List<SingleDateTimeType> getSingleDateTime() {
        if (singleDateTime == null) {
            singleDateTime = new ArrayList<SingleDateTimeType>();
        }
        return this.singleDateTime;
    }

    /**
     * Gets the value of the rangeOfDates property.
     * 
     * @return
     *     possible object is
     *     {@link TemporalCoverage.RangeOfDates }
     *     
     */
    public TemporalCoverage.RangeOfDates getRangeOfDates() {
        return rangeOfDates;
    }

    /**
     * Sets the value of the rangeOfDates property.
     * 
     * @param value
     *     allowed object is
     *     {@link TemporalCoverage.RangeOfDates }
     *     
     */
    public void setRangeOfDates(TemporalCoverage.RangeOfDates value) {
        this.rangeOfDates = value;
    }

    /**
     * Gets the value of the references property.
     * 
     * @return
     *     possible object is
     *     {@link au.org.ecoinformatics.eml.jaxb.eml.ViewType.References }
     *     
     */
    public au.org.ecoinformatics.eml.jaxb.eml.ViewType.References getReferences() {
        return references;
    }

    /**
     * Sets the value of the references property.
     * 
     * @param value
     *     allowed object is
     *     {@link au.org.ecoinformatics.eml.jaxb.eml.ViewType.References }
     *     
     */
    public void setReferences(au.org.ecoinformatics.eml.jaxb.eml.ViewType.References value) {
        this.references = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the id property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getId() {
        if (id == null) {
            id = new ArrayList<String>();
        }
        return this.id;
    }

    public TemporalCoverage withSingleDateTime(SingleDateTimeType... values) {
        if (values!= null) {
            for (SingleDateTimeType value: values) {
                getSingleDateTime().add(value);
            }
        }
        return this;
    }

    public TemporalCoverage withSingleDateTime(Collection<SingleDateTimeType> values) {
        if (values!= null) {
            getSingleDateTime().addAll(values);
        }
        return this;
    }

    public TemporalCoverage withRangeOfDates(TemporalCoverage.RangeOfDates value) {
        setRangeOfDates(value);
        return this;
    }

    public TemporalCoverage withReferences(au.org.ecoinformatics.eml.jaxb.eml.ViewType.References value) {
        setReferences(value);
        return this;
    }

    public TemporalCoverage withId(String... values) {
        if (values!= null) {
            for (String value: values) {
                getId().add(value);
            }
        }
        return this;
    }

    public TemporalCoverage withId(Collection<String> values) {
        if (values!= null) {
            getId().addAll(values);
        }
        return this;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="beginDate" type="{eml://ecoinformatics.org/coverage-2.1.1}SingleDateTimeType"/>
     *         &lt;element name="endDate" type="{eml://ecoinformatics.org/coverage-2.1.1}SingleDateTimeType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "beginDate",
        "endDate"
    })
    public static class RangeOfDates {

        @XmlElement(required = true)
        protected SingleDateTimeType beginDate;
        @XmlElement(required = true)
        protected SingleDateTimeType endDate;

        /**
         * Gets the value of the beginDate property.
         * 
         * @return
         *     possible object is
         *     {@link SingleDateTimeType }
         *     
         */
        public SingleDateTimeType getBeginDate() {
            return beginDate;
        }

        /**
         * Sets the value of the beginDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link SingleDateTimeType }
         *     
         */
        public void setBeginDate(SingleDateTimeType value) {
            this.beginDate = value;
        }

        /**
         * Gets the value of the endDate property.
         * 
         * @return
         *     possible object is
         *     {@link SingleDateTimeType }
         *     
         */
        public SingleDateTimeType getEndDate() {
            return endDate;
        }

        /**
         * Sets the value of the endDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link SingleDateTimeType }
         *     
         */
        public void setEndDate(SingleDateTimeType value) {
            this.endDate = value;
        }

        public TemporalCoverage.RangeOfDates withBeginDate(SingleDateTimeType value) {
            setBeginDate(value);
            return this;
        }

        public TemporalCoverage.RangeOfDates withEndDate(SingleDateTimeType value) {
            setEndDate(value);
            return this;
        }

    }

}
