//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.03 at 05:40:36 PM CST 
//


package au.org.ecoinformatics.eml.jaxb.eml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UnitType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UnitType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="standardUnit" type="{eml://ecoinformatics.org/units-2.1.1}StandardUnitDictionary"/>
 *         &lt;element name="customUnit" type="{eml://ecoinformatics.org/resource-2.1.1}NonEmptyStringType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UnitType", namespace = "eml://ecoinformatics.org/attribute-2.1.1", propOrder = {
    "standardUnit",
    "customUnit"
})
public class UnitType {

    protected String standardUnit;
    protected String customUnit;

    /**
     * Gets the value of the standardUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStandardUnit() {
        return standardUnit;
    }

    /**
     * Sets the value of the standardUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStandardUnit(String value) {
        this.standardUnit = value;
    }

    /**
     * Gets the value of the customUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomUnit() {
        return customUnit;
    }

    /**
     * Sets the value of the customUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomUnit(String value) {
        this.customUnit = value;
    }

    public UnitType withStandardUnit(String value) {
        setStandardUnit(value);
        return this;
    }

    public UnitType withCustomUnit(String value) {
        setCustomUnit(value);
        return this;
    }

}
